package lk.ultratech.agent.sys.bo;

public enum BOTypes {
    CEMENT_SHOP,PURCHASE_ORDER,CEMENT_AGENT,CEMENT,AGENT,SHOP,SHOP_ORDER,WORKER,WORKER_PAYMENT,DELIVERY,SHOP_DELIVERY,SHOP_PAYMENT,CHEQUE_PAYMENT;
}
