package lk.ultratech.agent.sys.dao;

public enum DAOType {
    AGENT,CEMENT,CEMENT_AGENT,CEMENT_SHOP,CHEQUE_PAYMENT,DELIVERY,PURCHASE_ORDER,SHOP,SHOP_DELIVERY,SHOP_ORDER,SHOP_PAYMENT,WORKER,WORKER_PAYMENT,QUERY;
}
